version: '3.1'

services:
    node:
        container_name: api-cubos
        image: node:14-alpine
        working_dir: /app
        volumes:
            - ./:/app
        env_file: ./.env
        command: ["yarn", "dev"]
        ports:
            - 4000:4000